server:
  port: 8888
  tomcat:
    uri-encoding: utf-8
  servlet:
    context-path: /

spring:
  application:
    name: hello-server
  profiles:
    active: dev

local:
  serverId: ${spring.application.name}

# actuator 配置
management:
  endpoints:
    web:
      exposure:
        # 开启所有端点
        include: "*"
  endpoint:
    health:
      # health 显示详细信息
      show-details: always
    # 开启shutdown端点，true 开启
    shutdown:
      enabled: false

# eureka 服务注册配置
eureka:
  client:
    service-url:
      # 指定注册中心
      defaultZone: http://peer1:1111/eureka/,http://peer2:1112/eureka/
