server:
  port: 8888
  tomcat:
    uri-encoding: utf-8
  servlet:
    context-path: /

spring:
  application:
    name: hello-server
  profiles:
    active: dev
  # 服务跟踪，默认0.1 在开发期间设置为1 全部收集
  sleuth:
    sampler:
      probability: 1
  # 直接收集
  zipkin:
    base-url: http://localhost:9060
    # 发送切换到 rabbit
#    sender: rabbit
#  rabbitmq:
#    host: localhost
#    port: 5672
#    username: springcloud
#    password: 123456
#    # 这里配置了重试策略
#    listener:
#      direct:
#        retry:
#          enabled: true
#      simple:
#        retry:
#          enabled: true

local:
  serverId: ${spring.application.name}

# actuator 配置
management:
  endpoints:
    web:
      exposure:
        # 开启所有端点
        include: "*"
  endpoint:
    health:
      # health 显示详细信息
      show-details: always
    # 开启shutdown端点，true 开启
    shutdown:
      enabled: false

# eureka 服务注册配置
eureka:
  client:
    service-url:
      # 指定注册中心
      defaultZone: http://peer1:1111/eureka/,http://peer2:1112/eureka/
