server:
  port: 9010
  tomcat:
    uri-encoding: utf-8
  servlet:
    context-path: /

spring:
  application:
    name: feign-consumer
#  # \u5F53\u9047\u5230\u540C\u6837\u540D\u5B57bean\u7684\u65F6\u5019\uFF0C\u662F\u5426\u5141\u8BB8\u8986\u76D6\u6CE8\u518C
#  main:
#    allow-bean-definition-overriding: true

#  profiles:
#    active: dev

# eureka \u670D\u52A1\u6CE8\u518C\u914D\u7F6E
eureka:
  client:
    service-url:
      # \u6307\u5B9A\u6CE8\u518C\u4E2D\u5FC3
      defaultZone: http://peer1:1111/eureka/

