server:
  port: 9010
  tomcat:
    uri-encoding: utf-8
  servlet:
    context-path: /

spring:
  application:
    name: feign-consumer
  # 开启bean重写
  main:
    allow-bean-definition-overriding: true
  # 服务跟踪，默认0.1 在开发期间设置为1 全部收集
  sleuth:
    sampler:
      probability: 1
  # 直接收集
  zipkin:
    base-url: http://localhost:9060
#    sender: rabbit
#  rabbitmq:
#    host: localhost
#    port: 5672
#    username: springcloud
#    password: 123456
#    # 这里配置了重试策略
#    listener:
#      direct:
#        retry:
#          enabled: true
#      simple:
#        retry:
#          enabled: true

#  profiles:
#    active: dev

eureka:
  client:
    service-url:
      defaultZone: http://peer1:1111/eureka/

hystrix:
  command:
    default:
      # 开启请求缓存 默认开启， 1降低请求线程消耗 2 降低请求响应
      requestCache:
        enabled: true
      execution:
        # 断路器`hystrix`的超时时间需要大于ribbon的超时时间，不然不会触发重试。
        isolation:
          thread:
            timeoutInMilliseconds: 3000

#ribbon:
#  #请求连接的超时时间
#  ConnectTimeout: 250
#  #请求处理的超时时间
#  ReadTimeout: 500
#  #对所有操作请求都进行重试
#  OkToRetryOnAllOperations: true
#  #切换实例的重试次数
#  MaxAutoRetriesNextServer: 2
#  #对当前实例的重试次数
#  MaxAutoRetries: 1
#  #根据如上配置，当访问到故障请求的时候，它会再尝试访问一次当前实例

hello-server:
  ribbon:
    #请求连接的超时时间
    ConnectTimeout: 250
    #请求处理的超时时间
    ReadTimeout: 1000
    #对所有操作请求都进行重试
    OkToRetryOnAllOperations: true
    #切换实例的重试次数
    MaxAutoRetriesNextServer: 2
    #对当前实例的重试次数
    MaxAutoRetries: 1
    #根据如上配置，当访问到故障请求的时候，它会再尝试访问一次当前实例

# 开启 hystrix
feign:
  hystrix:
    enabled: true
  compression:
    # 开启请求压缩功能
    request:
      enabled: true
      mime-types: text/xml,application/xml,application/json
      min-request-size: 2048
    response:
      enabled: true

# 服务跟踪