server:
  port: 1111

# 密码验证模式，需要添加security依赖
#security:
#  basic:
#    enabled: true
#  user:
#    name: user
#    password: 123


eureka:
  instance:
    hostname: localhost
    # 服务失效的时间，默认90秒
    lease-expiration-duration-in-seconds: 90
    # 服务续约任务的调用间隔时间， 默认30秒
    lease-renewal-interval-in-seconds: 30
  server:
    # 关闭安全监测
    enable-self-preservation: false
  client:
    # false 关闭注册
    register-with-eureka: true
    # false 检查服务
    fetch-registry: true
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka
      # 密码验证模式，需要添加security依赖
      # eureka.client.serviceUrl.defaultZone: http://user:123@${eureka.instance.hostname}:${server.port}/eureka
    # 修改缓存清单的更新时间，默认30秒
    registry-fetch-interval-seconds: 30

spring:
  profiles:
    active: peer1