server:
  port: 1111


eureka:
  instance:
    hostname: localhost
  server:
    # 关闭安全监测
    enable-self-preservation: false
  client:
    # false 关闭自己注册自己
    register-with-eureka: true
    # false 监测服务
    fetch-registry: true
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka

spring:
  profiles:
    active: peer1